steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    id: Build-Django
    args:
      - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_LIFECYCLE}/api:$COMMIT_SHA
      - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_LIFECYCLE}/api:latest
      - --context=./api
      - --cache=true
      - --cache-ttl=240h

  - name: "gcr.io/kaniko-project/executor:latest"
    id: Build-Nginx
    args:
      - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_LIFECYCLE}/nginx:$COMMIT_SHA
      - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_LIFECYCLE}/nginx:latest
      - --context=./nginx
      - --cache=true
      - --cache-ttl=240h

  - name: "gcr.io/walker-cpl/git-yq"
    id: Image-Update
    entrypoint: "bash"
    secretEnv: ["SSH_KEY"]
    args:
      - "-c"
      - |
        mkdir -p /root/.ssh
        echo "$$SSH_KEY" >> /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        cp known_hosts.github /root/.ssh/known_hosts

        git config --global user.email "walkernobrien@gmail.com"
        git config --global user.name "Walker O'Brien"
        git config --global pull.ff only

        git clone git@github.com:theboarderline/$REPO_NAME.git
        cd $REPO_NAME
        git checkout $BRANCH_NAME
        git fetch
        git pull

        source /usr/bin/update_image.sh ${_LIFECYCLE} $COMMIT_SHA

        git add -A
        git commit -m "Cloudbuild image update. new tag: $COMMIT_SHA"
        git push
        
        cd ../

  - name: "gcr.io/cloud-builders/gcloud-slim"
    id: Gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ ${_USE_HELM} ]]; then
          gcloud container clusters get-credentials ${_CLUSTER} --zone=${_ZONE} --project=${_GKE_PROJECT}
        fi

  - name: "gcr.io/walker-cpl/helm"
    id: Helm-Upgrade
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ ${_USE_HELM} ]]; then
          cd $REPO_NAME
          make all NAMESPACE=${_APP_CODE} LIFECYCLE=${_LIFECYCLE}
        fi
    env:
      - "CLOUDSDK_COMPUTE_ZONE=${_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/git-creds/versions/latest
      env: "SSH_KEY"

timeout: 900s
options:
  machineType: E2_HIGHCPU_8


