# Generated by Django 3.1.13 on 2021-10-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211010_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='can_text',
            field=models.BooleanField(default=True),
        ),
    ]
