# Generated by Django 3.1.13 on 2021-09-27 02:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_range_lower', models.IntegerField(default=0)),
                ('sell_range_upper', models.IntegerField(default=10000000)),
                ('display', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=16)),
                ('zipcode', models.IntegerField(default=0)),
                ('num_bed', models.IntegerField(default=0)),
                ('num_bath', models.IntegerField(default=0)),
                ('sq_ft', models.IntegerField(default=0)),
                ('basement_cond', models.CharField(max_length=16, null=True)),
                ('occupancy', models.CharField(max_length=16, null=True)),
                ('land_use', models.CharField(max_length=32, null=True)),
                ('construct_type', models.CharField(max_length=32, null=True)),
                ('property_tax', models.IntegerField(default=0)),
                ('assess_value', models.IntegerField(default=0)),
                ('notes', models.CharField(max_length=256, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=256)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house')),
            ],
        ),
    ]
