# Generated by Django 3.1.13 on 2021-10-10 10:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20210927_0204'),
        ('accounts', '0002_auto_20211010_0707'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_testimony', models.CharField(max_length=512)),
                ('short_description', models.CharField(max_length=256)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.deal')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member')),
            ],
        ),
    ]
