# Generated by Django 3.1.13 on 2021-10-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_testimony'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealtype',
            old_name='deal',
            new_name='deal_type',
        ),
    ]
