# Generated by Django 3.1.13 on 2021-10-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20211010_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='house',
        ),
    ]
