# Generated by Django 3.1.13 on 2021-10-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20211010_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='member_testimony',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
