# Generated by Django 3.1.13 on 2021-10-11 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20211010_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.deal'),
        ),
    ]
