# Generated by Django 3.1.13 on 2021-10-11 05:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_member_can_text'),
        ('leads', '0008_auto_20211011_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_testimonial', models.CharField(max_length=512, null=True)),
                ('short_description', models.CharField(max_length=256)),
                ('display', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.deal')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.member')),
            ],
            options={
                'verbose_name_plural': 'Testimonies',
            },
        ),
        migrations.DeleteModel(
            name='Testimony',
        ),
    ]
