# Generated by Django 3.1.13 on 2021-11-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20211011_0558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={},
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=1024),
        ),
    ]
